/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#define _GNU_SOURCE 
#include "chat.h"

char *host;
char *nickname;
CLIENT *clnt;
int lineas = 0;
int running = 1;
int writing = 0;


WINDOW  *mainWin, *inputWin, *chatWin, *chatWinBox, *inputWinBox;

void sigintHandler(int sig_num) {
	running = 0;
	printExit();

	sleep(10);
	endwin();
	clnt_destroy (clnt);
	exit(0);
}

void sendMessage(char *send) {
	char *buffer = (char*) malloc(sizeof(char));

	asprintf(&buffer, "%s: %s", nickname, send);

	void *result_2 = writechat_1(&buffer, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	free(buffer);
}

void programa_chat_1(char *host) {

	clnt = clnt_create (host, PROGRAMA_CHAT, VERSION_CHAT, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	char *input = (char*)malloc(sizeof(char));
	int size = 0;
	int ch;

	resetInputWindow(nickname);

	signal(SIGINT, sigintHandler);

	while (1) {
		wcursyncup(inputWin);
		ch = getch();

		if (ch == 127 || ch == KEY_LEFT) {
			if (size > 0) {
				printMessages("\b \0", 2);
				size--;
				input[size] = '\0';
			}
			else {
				printMessages("\b \0", 2);
			}

		}
		else if (ch != ERR) {
			
			input[size] = (char)ch;
			input = (char*)realloc(input, sizeof(char) * (size + 2)); 
			size++;

			if (ch == '\n') {
				input[size] = '\0';
				sendMessage(input);

				free(input);
				input = (char*)malloc(sizeof(char));
				size = 0;

				resetInputWindow(nickname);
			}
			else {
				printMessages((char *)&ch, 2);
			}		
		}
	}

	running = 0;
	free(input);
	clnt_destroy (clnt);
	
}


int main (int argc, char *argv[]) {

	if (argc < 3) {
		printf ("\nUsage: ./chat_client serverHost nickname\n");
		exit (1);
	}
	host = argv[1];
	nickname = argv[2];

	initVisual();
	printWelcomeMessage(nickname);

	//lanzamos thread para recibir los mensajes
	pthread_t thread_chat;
	if (pthread_create(&thread_chat, NULL, threadChat, NULL) != 0) {
        exit(-1);
    }

	programa_chat_1 (host);
	sleep(10);

	free(nickname);
	free(host);
	
	exit (0);
}
