/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>
#include <ncurses.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <pthread.h>



#ifdef __cplusplus
extern "C" {
#endif


//visual functions
void initVisual();
void printMessages(char *buffer,int win);
void printWelcomeMessage(char *nickname);
void printExit();
void resetInputWindow(char *buffer);


//handler functions
void *threadChat(void *arg);



#define PROGRAMA_CHAT 0x20000001
#define VERSION_CHAT 1

#if defined(__STDC__) || defined(__cplusplus)
#define getChat 1
extern  char ** getchat_1(int *, CLIENT *);
extern  char ** getchat_1_svc(int *, struct svc_req *);
#define writeChat 2
extern  void * writechat_1(char **, CLIENT *);
extern  void * writechat_1_svc(char **, struct svc_req *);
#define getLineas 3
extern  int * getlineas_1(void *, CLIENT *);
extern  int * getlineas_1_svc(void *, struct svc_req *);
extern int programa_chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getChat 1
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
#define writeChat 2
extern  void * writechat_1();
extern  void * writechat_1_svc();
#define getLineas 3
extern  int * getlineas_1();
extern  int * getlineas_1_svc();
extern int programa_chat_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
